#!/bin/sh
#
# ands-harvester  Startup script for the ANDS Harvester
# chkconfig: - 86 15
# description: The ANDS Harvester does harvesting.

### BEGIN INIT INFO
# Provides: 
# Required-Start: 
# Required-Stop: 
# Should-Start: 
# Should-Stop: 
# Default-Start: 
# Default-Stop: 
# Short-Description: This is the ANDS Harvester.
# Description: 
### END INIT INFO

# Source function library.
. /etc/init.d/functions

exec_python="/usr/local/bin/python3"
exec="/usr/local/harvester/harvester_daemon.py"

prog="ands-harvester"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

pidfile=/usr/local/harvester/daemon.pid
lockfile=/var/lock/subsys/$prog

start () {
    if [ $UID -ne 0 ] ; then
        echo $"User has insufficient privilege."
        exit 4
    fi
    [ -x $exec_python ] || exit 5
    [ -f $exec ] || exit 6
    echo -n $"Starting $prog: "
    $exec_python $exec start
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
}

stop () {
    if [ $UID -ne 0 ] ; then
        echo $"User has insufficient privilege."
        exit 4
    fi
    echo -n $"Stopping $prog: "
    $exec_python $exec stop
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
}

restart() {
    stop
    start
}

status() {
    if [ $UID -ne 0 ] ; then
        echo $"User has insufficient privilege."
        exit 4
    fi
    $exec_python $exec status
    retval=$?
    echo
}

usage() {
    echo $"Usage: $0 {start|stop|status|restart}"
}

case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    status)
        status
        ;;
    usage)
        usage
        exit 0
        ;;
    *)
        usage
        exit 2
esac
exit $?
# vim:syntax=sh
